version: "3"

networks:
  my-network:
    driver: bridge

services:
  service1:
    build: ./
    ports:
      - "3000:3000"
    networks:
      - my-network
  service2:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - my-network
